# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a65adde90ffd10adf6f5b1d6f45af6a7fd8b06d6c8b8895fa2e15a1d6d32610933ea57d88bf7f9b998e5b36cdc079c36c7162804744013579f89a96ad45fd68

test:
  secret_key_base: 7daf5f3036207bf6e52ebd0044006a1d90066d5975abffeeec735932101acf608ea05673b29e42eaa8a08b234c2d69ed37c604dd2506b90fbf4c6de44d2222cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
